name: safefy
description: "Cofre digital seguro para armazenamento de credenciais."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:

    flutter:
      sdk: flutter

    cupertino_icons: ^1.0.8
    drift: ^2.18.0
    sqlite3_flutter_libs: ^0.5.24
    path_provider: ^2.1.3
    path: ^1.9.0
    cryptography: ^2.7.0
    flutter_secure_storage: ^9.2.2
    file_picker: ^8.0.6

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

assets:
  - assets/images/
